CREATE TABLE `records` (
	`entry` INT(11) NOT NULL AUTO_INCREMENT,
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`name` TINYTEXT NOT NULL,
	`moves` SMALLINT(6) NOT NULL,
	`duration` MEDIUMINT(9) NOT NULL,
	PRIMARY KEY (`entry`)
)
COMMENT='Record system'
ENGINE=InnoDB
;